"""Demo data seeder for runloq.

Populates a fresh instance with a fictional company's backlog so the board,
ticket modal, search, and activity log all look rich — useful for demos,
screenshots, and kicking the tyres. Contains **zero** real data: the company
("Northwind", a fictional managed-data-pipeline SaaS), its projects, people,
and tickets are all invented.

Invoked via ``runloq seed`` (seed the current instance) or
``runloq init --demo`` (scaffold a demo config + seed in one step).

Agent/model fields only persist for ``assignee="claude"`` (by design — runloq
targets AI coding agents), so AI-driven demo tickets use ``claude`` as the
assignee; ``alice`` / ``bob`` / ``carol`` are the human teammates.
"""

import os

import core

# Fictional company config — projects, people, and the agents dir is left
# pointing at a path that won't exist in a demo instance, so agent-slug
# validation is skipped and realistic slugs (frontend-dev, backend-dev, …)
# are accepted.
DEMO_CONFIG_TEMPLATE = """\
# runloq.config.toml — runloq demo instance (fictional company "Northwind")
# Generated by `runloq init --demo`. All data here is invented.

[projects]
API = "API & Backend"
WEB = "Web App"
INF = "Infra & DevOps"
DATA = "Data Platform"
DOC = "Docs & DX"

[assignees]
list = ["claude", "alice", "bob", "carol"]

[models]
list = ["opus", "sonnet", "haiku"]

[agents]
# Realistic agent slugs are used in the demo. This path intentionally does not
# exist in a demo instance, which makes runloq skip agent-slug validation.
dir = ".claude/agents"

[paths]
state_dir = "state"

[dashboard]
host = "127.0.0.1"
port = 3002
"""

# Ordered so every referenced ticket (parent / blocker / link) is created
# before the ticket that references it. `key` is a local handle resolved to a
# real generated ID at seed time. `comments` is a list of dicts:
# {"message": str, "status": Optional[str], "files": [...], "refs": [...]}.
_TICKETS = [
    # --- Epic ---
    {
        "key": "E_DASH", "type": "epic", "project": "WEB", "priority": "P1",
        "title": "v2 dashboard redesign",
        "description": "Umbrella for the Q3 dashboard overhaul: new run-timeline, "
                       "connectors UX, dark mode, and a command palette. Goal is a "
                       "noticeably faster, calmer surface that scales past 10k runs.",
    },

    # --- Backend / API ---
    {
        "key": "API_IDEMP", "project": "API", "priority": "P0", "status": "in_progress",
        "assignee": "claude", "agent": "backend-dev", "model": "opus",
        "title": "Idempotency keys on the ingest endpoint",
        "description": "POST /v1/ingest must accept an Idempotency-Key header and "
                       "de-dupe retried writes within a 24h window. Store keys in "
                       "Redis with a TTL; collisions return the original 2xx body.",
        "comments": [
            {"message": "Header plumbed through; Redis SETNX guard landed behind a "
                        "feature flag. Still need the replay-the-stored-response path.",
             "files": ["api/routes/ingest.py", "api/idempotency.py"]},
        ],
    },
    {
        "key": "API_DLQ", "project": "API", "priority": "P1", "status": "todo",
        "assignee": "claude", "agent": "backend-dev", "model": "sonnet",
        "title": "Retry + dead-letter queue for failed webhook deliveries",
        "description": "Outbound webhooks currently drop on first failure. Add "
                       "exponential backoff (max 6 tries) and route exhausted "
                       "deliveries to a DLQ with a manual replay endpoint.",
        "blocked_by": ["API_IDEMP"],
    },
    {
        "key": "API_PAGE", "project": "API", "priority": "P2",
        "assignee": "claude", "agent": "backend-dev", "model": "sonnet",
        "title": "Cursor-based pagination for /v1/events",
        "description": "Offset pagination times out past ~50k rows. Switch to "
                       "keyset pagination on (created_at, id) and return an opaque "
                       "next-cursor token.",
        "comments": [
            {"message": "Shipped. Keyset on (created_at,id) with a base64 cursor; "
                        "p95 on the events list dropped from 1.8s to 90ms.",
             "status": "done", "files": ["api/routes/events.py"]},
        ],
    },
    {
        "key": "API_RL", "project": "API", "priority": "P1", "status": "todo",
        "assignee": "claude", "agent": "api-engineer", "model": "sonnet",
        "title": "Per-API-key rate limiting (sliding window)",
        "description": "Add a sliding-window limiter keyed by API key, default "
                       "600 req/min, 429 with Retry-After. Limits configurable per "
                       "plan tier.",
        "linked_to": ["API_DLQ"],
    },
    {
        "key": "API_5XX", "project": "API", "priority": "P0", "status": "in_progress",
        "assignee": "claude", "agent": "backend-dev", "model": "opus",
        "title": "5xx spike on /v1/ingest under burst load",
        "description": "Under bursts >2k rps the ingest endpoint returns 503s. "
                       "Suspect connection-pool exhaustion against Postgres. Repro "
                       "with the load harness, find the bottleneck, fix it.",
        "comments": [
            {"message": "Repro'd at 2.4k rps. pgbouncer pool maxed at 100; raising "
                        "it just moves the wall. Profiling the ingest transaction next.",
             "refs": ["loadtest/ingest_burst.md"]},
        ],
    },

    # --- Web / dashboard (children of the epic) ---
    {
        "key": "WEB_TIMELINE", "project": "WEB", "priority": "P1", "status": "in_progress",
        "parent": "E_DASH", "assignee": "claude", "agent": "frontend-dev", "model": "sonnet",
        "title": "Rebuild the pipeline run timeline view",
        "description": "Replace the table with a virtualized timeline so 10k+ runs "
                       "scroll smoothly. Group by pipeline, color by status, lazy-load "
                       "run details on expand.",
        "comments": [
            {"message": "Virtualization in with react-virtual; 10k runs scroll at 60fps. "
                        "Wiring the expand-to-detail panel now.",
             "files": ["web/src/views/Timeline.tsx"]},
        ],
    },
    {
        "key": "WEB_DARK", "project": "WEB", "priority": "P2", "status": "todo",
        "parent": "E_DASH", "assignee": "claude", "agent": "frontend-dev", "model": "sonnet",
        "title": "Dark mode pass on the dashboard",
        "description": "Audit every surface in dark mode: contrast, elevation, accent "
                       "usage. Fix the washed-out cards and the unreadable secondary text.",
    },
    {
        "key": "WEB_EMPTY", "project": "WEB", "priority": "P2", "status": "todo",
        "parent": "E_DASH", "assignee": "claude", "agent": "frontend-dev", "model": "haiku",
        "title": "Empty states for the connectors page",
        "description": "First-run users see a blank page. Add an illustrated empty "
                       "state with a primary 'Connect a source' CTA and three example "
                       "connectors.",
    },
    {
        "key": "WEB_PALETTE", "project": "WEB", "priority": "P3",
        "parent": "E_DASH", "assignee": "claude", "agent": "frontend-dev", "model": "sonnet",
        "title": "Command palette (Ctrl+K) for quick nav",
        "description": "Fuzzy-search across pipelines, runs, and settings. Keyboard-first, "
                       "recent items on top.",
        "comments": [
            {"message": "Done — cmdk-based palette, fuzzy match on name+id, recents "
                        "persisted to localStorage.", "status": "done",
             "files": ["web/src/components/CommandPalette.tsx"]},
        ],
    },
    {
        "key": "WEB_OVERFLOW", "project": "WEB", "priority": "P3", "status": "todo",
        "assignee": "claude", "agent": "frontend-dev", "model": "haiku",
        "title": "Long pipeline names overflow the board cards",
        "description": "Truncate with an ellipsis and show the full name on hover/title.",
    },

    # --- Infra / DevOps ---
    {
        "key": "INF_AUTOSCALE", "project": "INF", "priority": "P1", "status": "in_progress",
        "assignee": "claude", "agent": "devops", "model": "sonnet",
        "title": "Migrate ingest workers to an autoscaling pool",
        "description": "Move the fixed worker fleet to a queue-depth-driven autoscaler "
                       "(scale 4→40 on lag). Add scale-in cooldown to avoid flapping.",
    },
    {
        "key": "INF_PG", "project": "INF", "priority": "P0", "status": "todo",
        "assignee": "claude", "agent": "dba", "model": "opus",
        "title": "Zero-downtime Postgres major upgrade (14 → 16)",
        "description": "Plan and execute a logical-replication-based major upgrade with "
                       "a rehearsed cutover and a tested rollback. Coordinate a read-only "
                       "window of <30s.",
        "blocked_by": ["INF_AUTOSCALE"],
    },
    {
        "key": "INF_GRAFANA", "project": "INF", "priority": "P3",
        "assignee": "claude", "agent": "devops", "model": "haiku",
        "title": "Grafana board for queue depth + worker lag",
        "description": "Per-pipeline queue depth, worker utilization, and end-to-end lag, "
                       "with alerts at >5m lag.",
        "comments": [
            {"message": "Board live; alert wired to the on-call channel at 5m lag.",
             "status": "done"},
        ],
    },
    {
        "key": "INF_CVE", "project": "INF", "priority": "P2", "status": "scheduled",
        "assignee": "claude", "agent": "security-engineer", "model": "sonnet",
        "title": "Monthly dependency + CVE sweep",
        "description": "Audit prod dependencies for known CVEs, bump and test, file "
                       "follow-ups for anything that can't be patched cleanly.",
        "scheduled_at": "2026-07-01T09:00", "recurrence": "monthly",
    },

    # --- Data platform ---
    {
        "key": "DATA_BACKFILL", "project": "DATA", "priority": "P1", "status": "todo",
        "assignee": "claude", "agent": "data-engineer", "model": "sonnet",
        "title": "Backfill job for late-arriving events",
        "description": "Events that land >1h late are dropped from the rollups. Add an "
                       "idempotent backfill that reprocesses a window without "
                       "double-counting.",
    },
    {
        "key": "DATA_LINEAGE", "project": "DATA", "priority": "P2",
        "assignee": "claude", "agent": "data-engineer", "model": "sonnet",
        "title": "Lineage tags on the warehouse models",
        "description": "Tag every dbt model with source + owner so the catalog can "
                       "render end-to-end lineage.",
        "comments": [
            {"message": "All 84 models tagged; catalog renders full lineage now.",
             "status": "done"},
        ],
    },
    {
        "key": "QA_FLAKY", "project": "DATA", "priority": "P2", "status": "todo",
        "assignee": "claude", "agent": "qa", "model": "haiku",
        "title": "Flaky e2e: connector OAuth callback",
        "description": "The OAuth-callback e2e fails ~1 in 5 runs in CI. Root-cause the "
                       "race (suspect the redirect lands before the session cookie is "
                       "set) and stabilize it.",
    },

    # --- Human-owned tickets ---
    {
        "key": "DOC_SELFHOST", "project": "DOC", "priority": "P2", "status": "todo",
        "assignee": "alice",
        "title": "Write the 'self-host in 10 minutes' guide",
        "description": "Step-by-step Docker Compose walkthrough from zero to a running "
                       "instance, with the gotchas we keep getting support tickets about.",
    },
    {
        "key": "DOC_TOUR", "project": "DOC", "priority": "P3", "status": "todo",
        "assignee": "bob",
        "title": "Record a 2-minute product tour",
        "description": "Short screen recording: connect a source → see runs → drill into "
                       "a failure. For the landing page hero.",
    },
    {
        "key": "RES_ONBOARD", "project": "WEB", "priority": "P2", "status": "todo",
        "assignee": "carol",
        "title": "Synthesize the onboarding-friction interviews",
        "description": "Pull themes from the 8 customer interviews on first-run friction; "
                       "turn the top 3 into tickets.",
    },
]


def seed_demo(db, *, force=False):
    """Seed the database with the fictional Northwind backlog.

    Idempotent guard: refuses to run if the DB already holds issues, unless
    ``force=True``. Returns the number of issues created.
    """
    existing = db.execute("SELECT COUNT(*) FROM issues").fetchone()[0]
    if existing and not force:
        raise SystemExit(
            f"Refusing to seed: {existing} issue(s) already exist. "
            "Pass --force to seed on top of existing data (demo instances only)."
        )

    # The demo uses illustrative agent slugs (backend-dev, frontend-dev, …) that
    # won't have matching files in a fresh instance. Seeding fictional data is
    # exactly the case for skipping agent-slug validation.
    prev_skip = os.environ.get("TRACKER_SKIP_AGENT_VALIDATION")
    os.environ["TRACKER_SKIP_AGENT_VALIDATION"] = "1"
    try:
        return _seed(db)
    finally:
        if prev_skip is None:
            os.environ.pop("TRACKER_SKIP_AGENT_VALIDATION", None)
        else:
            os.environ["TRACKER_SKIP_AGENT_VALIDATION"] = prev_skip


def _seed(db):
    ids: dict[str, str] = {}
    created = 0

    for spec in _TICKETS:
        key = spec["key"]
        parent = spec.get("parent")
        blocked = [ids[k] for k in spec.get("blocked_by", [])]
        linked = [ids[k] for k in spec.get("linked_to", [])]

        row = core.create_issue(
            db,
            title=spec["title"],
            project=spec.get("project", "API"),
            type=spec.get("type", "issue"),
            priority=spec.get("priority", "P2"),
            assignee=spec.get("assignee", "claude"),
            agent=spec.get("agent"),
            model=spec.get("model"),
            description=spec.get("description"),
            blocked_by=blocked or None,
            linked_to=linked or None,
            parent_id=ids.get(parent) if parent else None,
            scheduled_at=spec.get("scheduled_at"),
            recurrence=spec.get("recurrence"),
            status=spec.get("status"),
        )
        ids[key] = row["id"]
        created += 1

        for c in spec.get("comments", []):
            core.add_comment(
                db, row["id"], c["message"],
                status=c.get("status"),
                files=c.get("files"),
                refs=c.get("refs"),
            )

    db.commit()
    return created
